# Axes
axis_vx: 5 #changed from ps3
axis_vy: 2
axis_vw: 0
axis_pan: 0
axis_tilt: 5 #changed from ps3

# base velocities
max_vw: 0.8
max_vx: 0.5
max_vy: 0.5
max_vw_run: 1.4
max_vx_run: 1.0
max_vy_run: 1.0

# Head 
max_pan: 2.7
max_tilt: 1.4
min_tilt: -0.4
tilt_step: 0.3
pan_step: 0.3

# Buttons have changed for PS3 controller mapping 
# With joystick remapper, this works with all joysticks on "/joy" 
run_button: 5 # changed from ps3
torso_dn_button: 1 #changed from ps3
torso_up_button: 3 #changed from ps3
head_button: 6 # changed from ps3
deadman_button: 4 # changed from ps3
